[tool.poetry]
name = "tdd-api"
version = "0.1.0"
description = ""
authors = ["VicAlexv <Victor2013sbc@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
